# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: battle.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import game_data_pb2 as game__data__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x62\x61ttle.proto\x1a\x0fgame_data.proto\".\n\x0b\x42\x61ttleBatch\x12\x1f\n\x07\x62\x61ttles\x18\x01 \x03(\x0b\x32\x0e.BattleSummary\"\xc1\x06\n\rBattleSummary\x12\x0c\n\x04seed\x18\x01 \x01(\t\x12(\n\x06player\x18\x02 \x01(\x0b\x32\x18.BattleSummary.TrainerID\x12\'\n\x05\x65nemy\x18\x03 \x01(\x0b\x32\x18.BattleSummary.TrainerID\x12%\n\x06winner\x18\x04 \x01(\x0e\x32\x15.BattleSummary.Winner\x12,\n\x05turns\x18\x05 \x03(\x0b\x32\x1d.BattleSummary.TurnDescriptor\x1a\x34\n\tTrainerID\x12\x15\n\rtrainer_class\x18\x01 \x01(\r\x12\x10\n\x08instance\x18\x02 \x01(\r\x1a\xf3\x03\n\x0eTurnDescriptor\x12\x13\n\x0bturn_number\x18\x01 \x01(\r\x12=\n\x0fselected_action\x18\x02 \x01(\x0e\x32$.BattleSummary.TurnDescriptor.Action\x12(\n\rselected_move\x18\x03 \x01(\x0e\x32\x0f.MoveIdentifierH\x00\x12(\n\rselected_item\x18\x04 \x01(\x0e\x32\x0f.ItemIdentifierH\x00\x12\x1a\n\x10selected_pokemon\x18\x05 \x01(\rH\x00\x12;\n\nplayer_mon\x18\x06 \x01(\x0b\x32\'.BattleSummary.TurnDescriptor.BattleMon\x12:\n\tenemy_mon\x18\x07 \x01(\x0b\x32\'.BattleSummary.TurnDescriptor.BattleMon\x1a^\n\tBattleMon\x12 \n\x07species\x18\x01 \x01(\x0e\x32\x0f.PokemonSpecies\x12\n\n\x02hp\x18\x02 \x01(\r\x12\x0e\n\x06max_hp\x18\x03 \x01(\r\x12\x13\n\x0bparty_index\x18\x04 \x01(\r\":\n\x06\x41\x63tion\x12\x08\n\x04MOVE\x10\x00\x12\n\n\x06SWITCH\x10\x01\x12\x08\n\x04ITEM\x10\x02\x12\x10\n\x0c\x46ORCE_SWITCH\x10\x03\x42\x08\n\x06\x61\x63tion\"N\n\x06Winner\x12\n\n\x06PLAYER\x10\x00\x12\t\n\x05\x45NEMY\x10\x01\x12\x16\n\x12\x44RAW_BY_TURN_COUNT\x10\x02\x12\x15\n\x11\x44RAW_BY_EXCEPTION\x10\x03\x62\x06proto3')



_BATTLEBATCH = DESCRIPTOR.message_types_by_name['BattleBatch']
_BATTLESUMMARY = DESCRIPTOR.message_types_by_name['BattleSummary']
_BATTLESUMMARY_TRAINERID = _BATTLESUMMARY.nested_types_by_name['TrainerID']
_BATTLESUMMARY_TURNDESCRIPTOR = _BATTLESUMMARY.nested_types_by_name['TurnDescriptor']
_BATTLESUMMARY_TURNDESCRIPTOR_BATTLEMON = _BATTLESUMMARY_TURNDESCRIPTOR.nested_types_by_name['BattleMon']
_BATTLESUMMARY_TURNDESCRIPTOR_ACTION = _BATTLESUMMARY_TURNDESCRIPTOR.enum_types_by_name['Action']
_BATTLESUMMARY_WINNER = _BATTLESUMMARY.enum_types_by_name['Winner']
BattleBatch = _reflection.GeneratedProtocolMessageType('BattleBatch', (_message.Message,), {
  'DESCRIPTOR' : _BATTLEBATCH,
  '__module__' : 'battle_pb2'
  # @@protoc_insertion_point(class_scope:BattleBatch)
  })
_sym_db.RegisterMessage(BattleBatch)

BattleSummary = _reflection.GeneratedProtocolMessageType('BattleSummary', (_message.Message,), {

  'TrainerID' : _reflection.GeneratedProtocolMessageType('TrainerID', (_message.Message,), {
    'DESCRIPTOR' : _BATTLESUMMARY_TRAINERID,
    '__module__' : 'battle_pb2'
    # @@protoc_insertion_point(class_scope:BattleSummary.TrainerID)
    })
  ,

  'TurnDescriptor' : _reflection.GeneratedProtocolMessageType('TurnDescriptor', (_message.Message,), {

    'BattleMon' : _reflection.GeneratedProtocolMessageType('BattleMon', (_message.Message,), {
      'DESCRIPTOR' : _BATTLESUMMARY_TURNDESCRIPTOR_BATTLEMON,
      '__module__' : 'battle_pb2'
      # @@protoc_insertion_point(class_scope:BattleSummary.TurnDescriptor.BattleMon)
      })
    ,
    'DESCRIPTOR' : _BATTLESUMMARY_TURNDESCRIPTOR,
    '__module__' : 'battle_pb2'
    # @@protoc_insertion_point(class_scope:BattleSummary.TurnDescriptor)
    })
  ,
  'DESCRIPTOR' : _BATTLESUMMARY,
  '__module__' : 'battle_pb2'
  # @@protoc_insertion_point(class_scope:BattleSummary)
  })
_sym_db.RegisterMessage(BattleSummary)
_sym_db.RegisterMessage(BattleSummary.TrainerID)
_sym_db.RegisterMessage(BattleSummary.TurnDescriptor)
_sym_db.RegisterMessage(BattleSummary.TurnDescriptor.BattleMon)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _BATTLEBATCH._serialized_start=33
  _BATTLEBATCH._serialized_end=79
  _BATTLESUMMARY._serialized_start=82
  _BATTLESUMMARY._serialized_end=915
  _BATTLESUMMARY_TRAINERID._serialized_start=281
  _BATTLESUMMARY_TRAINERID._serialized_end=333
  _BATTLESUMMARY_TURNDESCRIPTOR._serialized_start=336
  _BATTLESUMMARY_TURNDESCRIPTOR._serialized_end=835
  _BATTLESUMMARY_TURNDESCRIPTOR_BATTLEMON._serialized_start=671
  _BATTLESUMMARY_TURNDESCRIPTOR_BATTLEMON._serialized_end=765
  _BATTLESUMMARY_TURNDESCRIPTOR_ACTION._serialized_start=767
  _BATTLESUMMARY_TURNDESCRIPTOR_ACTION._serialized_end=825
  _BATTLESUMMARY_WINNER._serialized_start=837
  _BATTLESUMMARY_WINNER._serialized_end=915
# @@protoc_insertion_point(module_scope)
