from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from typing import ClassVar

ABRA: PokemonSpecies
ABSORB: MoveIdentifier
ACID: MoveIdentifier
ACID_ARMOR: MoveIdentifier
AEROBLAST: MoveIdentifier
AERODACTYL: PokemonSpecies
AGILITY: MoveIdentifier
AIPOM: PokemonSpecies
ALAKAZAM: PokemonSpecies
AMNESIA: MoveIdentifier
AMPHAROS: PokemonSpecies
ANCIENTPOWER: MoveIdentifier
ARBOK: PokemonSpecies
ARCANINE: PokemonSpecies
ARIADOS: PokemonSpecies
ARTICUNO: PokemonSpecies
ATTRACT: MoveIdentifier
AURORA_BEAM: MoveIdentifier
AZUMARILL: PokemonSpecies
BARRAGE: MoveIdentifier
BARRIER: MoveIdentifier
BATON_PASS: MoveIdentifier
BAYLEEF: PokemonSpecies
BEAT_UP: MoveIdentifier
BEEDRILL: PokemonSpecies
BELLOSSOM: PokemonSpecies
BELLSPROUT: PokemonSpecies
BELLY_DRUM: MoveIdentifier
BIDE: MoveIdentifier
BIND: MoveIdentifier
BITE: MoveIdentifier
BLASTOISE: PokemonSpecies
BLISSEY: PokemonSpecies
BLIZZARD: MoveIdentifier
BODY_SLAM: MoveIdentifier
BONEMERANG: MoveIdentifier
BONE_CLUB: MoveIdentifier
BONE_RUSH: MoveIdentifier
BUBBLE: MoveIdentifier
BUBBLEBEAM: MoveIdentifier
BULBASAUR: PokemonSpecies
BUTTERFREE: PokemonSpecies
CATERPIE: PokemonSpecies
CELEBI: PokemonSpecies
CHANSEY: PokemonSpecies
CHARIZARD: PokemonSpecies
CHARM: MoveIdentifier
CHARMANDER: PokemonSpecies
CHARMELEON: PokemonSpecies
CHIKORITA: PokemonSpecies
CHINCHOU: PokemonSpecies
CLAMP: MoveIdentifier
CLEFABLE: PokemonSpecies
CLEFAIRY: PokemonSpecies
CLEFFA: PokemonSpecies
CLOYSTER: PokemonSpecies
COMET_PUNCH: MoveIdentifier
CONFUSE_RAY: MoveIdentifier
CONFUSION: MoveIdentifier
CONSTRICT: MoveIdentifier
CONVERSION: MoveIdentifier
CONVERSION2: MoveIdentifier
CORSOLA: PokemonSpecies
COTTON_SPORE: MoveIdentifier
COUNTER: MoveIdentifier
CRABHAMMER: MoveIdentifier
CROBAT: PokemonSpecies
CROCONAW: PokemonSpecies
CROSS_CHOP: MoveIdentifier
CRUNCH: MoveIdentifier
CUBONE: PokemonSpecies
CURSE: MoveIdentifier
CUT: MoveIdentifier
CYNDAQUIL: PokemonSpecies
DEFENSE_CURL: MoveIdentifier
DELIBIRD: PokemonSpecies
DESCRIPTOR: _descriptor.FileDescriptor
DESTINY_BOND: MoveIdentifier
DETECT: MoveIdentifier
DEWGONG: PokemonSpecies
DIG: MoveIdentifier
DIGLETT: PokemonSpecies
DIRE_HIT: ItemIdentifier
DISABLE: MoveIdentifier
DITTO: PokemonSpecies
DIZZY_PUNCH: MoveIdentifier
DODRIO: PokemonSpecies
DODUO: PokemonSpecies
DONPHAN: PokemonSpecies
DOUBLESLAP: MoveIdentifier
DOUBLE_EDGE: MoveIdentifier
DOUBLE_KICK: MoveIdentifier
DOUBLE_TEAM: MoveIdentifier
DRAGONAIR: PokemonSpecies
DRAGONBREATH: MoveIdentifier
DRAGONITE: PokemonSpecies
DRAGON_RAGE: MoveIdentifier
DRATINI: PokemonSpecies
DREAM_EATER: MoveIdentifier
DRILL_PECK: MoveIdentifier
DROWZEE: PokemonSpecies
DUGTRIO: PokemonSpecies
DUNSPARCE: PokemonSpecies
DYNAMICPUNCH: MoveIdentifier
EARTHQUAKE: MoveIdentifier
EEVEE: PokemonSpecies
EGG_BOMB: MoveIdentifier
EKANS: PokemonSpecies
ELECTABUZZ: PokemonSpecies
ELECTRODE: PokemonSpecies
ELEKID: PokemonSpecies
EMBER: MoveIdentifier
ENCORE: MoveIdentifier
ENDURE: MoveIdentifier
ENTEI: PokemonSpecies
ESPEON: PokemonSpecies
EXEGGCUTE: PokemonSpecies
EXEGGUTOR: PokemonSpecies
EXPLOSION: MoveIdentifier
EXTREMESPEED: MoveIdentifier
FAINT_ATTACK: MoveIdentifier
FALSE_SWIPE: MoveIdentifier
FARFETCH_D: PokemonSpecies
FEAROW: PokemonSpecies
FERALIGATR: PokemonSpecies
FIRE_BLAST: MoveIdentifier
FIRE_PUNCH: MoveIdentifier
FIRE_SPIN: MoveIdentifier
FISSURE: MoveIdentifier
FLAAFFY: PokemonSpecies
FLAIL: MoveIdentifier
FLAMETHROWER: MoveIdentifier
FLAME_WHEEL: MoveIdentifier
FLAREON: PokemonSpecies
FLASH: MoveIdentifier
FLY: MoveIdentifier
FOCUS_ENERGY: MoveIdentifier
FORESIGHT: MoveIdentifier
FORRETRESS: PokemonSpecies
FRUSTRATION: MoveIdentifier
FULL_HEAL: ItemIdentifier
FULL_RESTORE: ItemIdentifier
FURRET: PokemonSpecies
FURY_ATTACK: MoveIdentifier
FURY_CUTTER: MoveIdentifier
FURY_SWIPES: MoveIdentifier
FUTURE_SIGHT: MoveIdentifier
GASTLY: PokemonSpecies
GENGAR: PokemonSpecies
GEODUDE: PokemonSpecies
GIGA_DRAIN: MoveIdentifier
GIRAFARIG: PokemonSpecies
GLARE: MoveIdentifier
GLIGAR: PokemonSpecies
GLOOM: PokemonSpecies
GOLBAT: PokemonSpecies
GOLDEEN: PokemonSpecies
GOLDUCK: PokemonSpecies
GOLEM: PokemonSpecies
GRANBULL: PokemonSpecies
GRAVELER: PokemonSpecies
GRIMER: PokemonSpecies
GROWL: MoveIdentifier
GROWLITHE: PokemonSpecies
GROWTH: MoveIdentifier
GUARD_SPEC: ItemIdentifier
GUILLOTINE: MoveIdentifier
GUST: MoveIdentifier
GYARADOS: PokemonSpecies
HARDEN: MoveIdentifier
HAUNTER: PokemonSpecies
HAZE: MoveIdentifier
HEADBUTT: MoveIdentifier
HEAL_BELL: MoveIdentifier
HERACROSS: PokemonSpecies
HIDDEN_POWER: MoveIdentifier
HITMONCHAN: PokemonSpecies
HITMONLEE: PokemonSpecies
HITMONTOP: PokemonSpecies
HI_JUMP_KICK: MoveIdentifier
HOOTHOOT: PokemonSpecies
HOPPIP: PokemonSpecies
HORN_ATTACK: MoveIdentifier
HORN_DRILL: MoveIdentifier
HORSEA: PokemonSpecies
HOUNDOOM: PokemonSpecies
HOUNDOUR: PokemonSpecies
HO_OH: PokemonSpecies
HYDRO_PUMP: MoveIdentifier
HYPER_BEAM: MoveIdentifier
HYPER_FANG: MoveIdentifier
HYPER_POTION: ItemIdentifier
HYPNO: PokemonSpecies
HYPNOSIS: MoveIdentifier
ICE_BEAM: MoveIdentifier
ICE_PUNCH: MoveIdentifier
ICY_WIND: MoveIdentifier
IGGLYBUFF: PokemonSpecies
IRON_TAIL: MoveIdentifier
IVYSAUR: PokemonSpecies
JIGGLYPUFF: PokemonSpecies
JOLTEON: PokemonSpecies
JUMPLUFF: PokemonSpecies
JUMP_KICK: MoveIdentifier
JYNX: PokemonSpecies
KABUTO: PokemonSpecies
KABUTOPS: PokemonSpecies
KADABRA: PokemonSpecies
KAKUNA: PokemonSpecies
KANGASKHAN: PokemonSpecies
KARATE_CHOP: MoveIdentifier
KINESIS: MoveIdentifier
KINGDRA: PokemonSpecies
KINGLER: PokemonSpecies
KOFFING: PokemonSpecies
KRABBY: PokemonSpecies
LANTURN: PokemonSpecies
LAPRAS: PokemonSpecies
LARVITAR: PokemonSpecies
LEDIAN: PokemonSpecies
LEDYBA: PokemonSpecies
LEECH_LIFE: MoveIdentifier
LEECH_SEED: MoveIdentifier
LEER: MoveIdentifier
LICK: MoveIdentifier
LICKITUNG: PokemonSpecies
LIGHT_SCREEN: MoveIdentifier
LOCK_ON: MoveIdentifier
LOVELY_KISS: MoveIdentifier
LOW_KICK: MoveIdentifier
LUGIA: PokemonSpecies
MACHAMP: PokemonSpecies
MACHOKE: PokemonSpecies
MACHOP: PokemonSpecies
MACH_PUNCH: MoveIdentifier
MAGBY: PokemonSpecies
MAGCARGO: PokemonSpecies
MAGIKARP: PokemonSpecies
MAGMAR: PokemonSpecies
MAGNEMITE: PokemonSpecies
MAGNETON: PokemonSpecies
MAGNITUDE: MoveIdentifier
MANKEY: PokemonSpecies
MANTINE: PokemonSpecies
MAREEP: PokemonSpecies
MARILL: PokemonSpecies
MAROWAK: PokemonSpecies
MAX_POTION: ItemIdentifier
MEAN_LOOK: MoveIdentifier
MEDITATE: MoveIdentifier
MEGAHORN: MoveIdentifier
MEGANIUM: PokemonSpecies
MEGA_DRAIN: MoveIdentifier
MEGA_KICK: MoveIdentifier
MEGA_PUNCH: MoveIdentifier
MEOWTH: PokemonSpecies
METAL_CLAW: MoveIdentifier
METAPOD: PokemonSpecies
METRONOME: MoveIdentifier
MEW: PokemonSpecies
MEWTWO: PokemonSpecies
MILK_DRINK: MoveIdentifier
MILTANK: PokemonSpecies
MIMIC: MoveIdentifier
MIND_READER: MoveIdentifier
MINIMIZE: MoveIdentifier
MIRROR_COAT: MoveIdentifier
MIRROR_MOVE: MoveIdentifier
MISDREAVUS: PokemonSpecies
MIST: MoveIdentifier
MOLTRES: PokemonSpecies
MOONLIGHT: MoveIdentifier
MORNING_SUN: MoveIdentifier
MR_MIME: PokemonSpecies
MUD_SLAP: MoveIdentifier
MUK: PokemonSpecies
MURKROW: PokemonSpecies
NATU: PokemonSpecies
NIDOKING: PokemonSpecies
NIDOQUEEN: PokemonSpecies
NIDORAN_F: PokemonSpecies
NIDORAN_M: PokemonSpecies
NIDORINA: PokemonSpecies
NIDORINO: PokemonSpecies
NIGHTMARE: MoveIdentifier
NIGHT_SHADE: MoveIdentifier
NINETALES: PokemonSpecies
NOCTOWL: PokemonSpecies
OCTAZOOKA: MoveIdentifier
OCTILLERY: PokemonSpecies
ODDISH: PokemonSpecies
OMANYTE: PokemonSpecies
OMASTAR: PokemonSpecies
ONIX: PokemonSpecies
OUTRAGE: MoveIdentifier
PAIN_SPLIT: MoveIdentifier
PARAS: PokemonSpecies
PARASECT: PokemonSpecies
PAY_DAY: MoveIdentifier
PECK: MoveIdentifier
PERISH_SONG: MoveIdentifier
PERSIAN: PokemonSpecies
PETAL_DANCE: MoveIdentifier
PHANPY: PokemonSpecies
PICHU: PokemonSpecies
PIDGEOT: PokemonSpecies
PIDGEOTTO: PokemonSpecies
PIDGEY: PokemonSpecies
PIKACHU: PokemonSpecies
PILOSWINE: PokemonSpecies
PINECO: PokemonSpecies
PINSIR: PokemonSpecies
PIN_MISSILE: MoveIdentifier
POISONPOWDER: MoveIdentifier
POISON_GAS: MoveIdentifier
POISON_STING: MoveIdentifier
POLITOED: PokemonSpecies
POLIWAG: PokemonSpecies
POLIWHIRL: PokemonSpecies
POLIWRATH: PokemonSpecies
PONYTA: PokemonSpecies
PORYGON: PokemonSpecies
PORYGON2: PokemonSpecies
POTION: ItemIdentifier
POUND: MoveIdentifier
POWDER_SNOW: MoveIdentifier
PRESENT: MoveIdentifier
PRIMEAPE: PokemonSpecies
PROTECT: MoveIdentifier
PSYBEAM: MoveIdentifier
PSYCHIC_M: MoveIdentifier
PSYCH_UP: MoveIdentifier
PSYDUCK: PokemonSpecies
PSYWAVE: MoveIdentifier
PUPITAR: PokemonSpecies
PURSUIT: MoveIdentifier
QUAGSIRE: PokemonSpecies
QUICK_ATTACK: MoveIdentifier
QUILAVA: PokemonSpecies
QWILFISH: PokemonSpecies
RAGE: MoveIdentifier
RAICHU: PokemonSpecies
RAIKOU: PokemonSpecies
RAIN_DANCE: MoveIdentifier
RAPIDASH: PokemonSpecies
RAPID_SPIN: MoveIdentifier
RATICATE: PokemonSpecies
RATTATA: PokemonSpecies
RAZOR_LEAF: MoveIdentifier
RAZOR_WIND: MoveIdentifier
RECOVER: MoveIdentifier
REFLECT: MoveIdentifier
REMORAID: PokemonSpecies
REST: MoveIdentifier
RETURN: MoveIdentifier
REVERSAL: MoveIdentifier
RHYDON: PokemonSpecies
RHYHORN: PokemonSpecies
ROAR: MoveIdentifier
ROCK_SLIDE: MoveIdentifier
ROCK_SMASH: MoveIdentifier
ROCK_THROW: MoveIdentifier
ROLLING_KICK: MoveIdentifier
ROLLOUT: MoveIdentifier
SACRED_FIRE: MoveIdentifier
SAFEGUARD: MoveIdentifier
SANDSHREW: PokemonSpecies
SANDSLASH: PokemonSpecies
SANDSTORM: MoveIdentifier
SAND_ATTACK: MoveIdentifier
SCARY_FACE: MoveIdentifier
SCIZOR: PokemonSpecies
SCRATCH: MoveIdentifier
SCREECH: MoveIdentifier
SCYTHER: PokemonSpecies
SEADRA: PokemonSpecies
SEAKING: PokemonSpecies
SEEL: PokemonSpecies
SEISMIC_TOSS: MoveIdentifier
SELFDESTRUCT: MoveIdentifier
SENTRET: PokemonSpecies
SHADOW_BALL: MoveIdentifier
SHARPEN: MoveIdentifier
SHELLDER: PokemonSpecies
SHUCKLE: PokemonSpecies
SING: MoveIdentifier
SKARMORY: PokemonSpecies
SKETCH: MoveIdentifier
SKIPLOOM: PokemonSpecies
SKULL_BASH: MoveIdentifier
SKY_ATTACK: MoveIdentifier
SLAM: MoveIdentifier
SLASH: MoveIdentifier
SLEEP_POWDER: MoveIdentifier
SLEEP_TALK: MoveIdentifier
SLOWBRO: PokemonSpecies
SLOWKING: PokemonSpecies
SLOWPOKE: PokemonSpecies
SLUDGE: MoveIdentifier
SLUDGE_BOMB: MoveIdentifier
SLUGMA: PokemonSpecies
SMEARGLE: PokemonSpecies
SMOG: MoveIdentifier
SMOKESCREEN: MoveIdentifier
SMOOCHUM: PokemonSpecies
SNEASEL: PokemonSpecies
SNORE: MoveIdentifier
SNORLAX: PokemonSpecies
SNUBBULL: PokemonSpecies
SOFTBOILED: MoveIdentifier
SOLARBEAM: MoveIdentifier
SONICBOOM: MoveIdentifier
SPARK: MoveIdentifier
SPEAROW: PokemonSpecies
SPIDER_WEB: MoveIdentifier
SPIKES: MoveIdentifier
SPIKE_CANNON: MoveIdentifier
SPINARAK: PokemonSpecies
SPITE: MoveIdentifier
SPLASH: MoveIdentifier
SPORE: MoveIdentifier
SQUIRTLE: PokemonSpecies
STANTLER: PokemonSpecies
STARMIE: PokemonSpecies
STARYU: PokemonSpecies
STEELIX: PokemonSpecies
STEEL_WING: MoveIdentifier
STOMP: MoveIdentifier
STRENGTH: MoveIdentifier
STRING_SHOT: MoveIdentifier
STRUGGLE: MoveIdentifier
STUN_SPORE: MoveIdentifier
SUBMISSION: MoveIdentifier
SUBSTITUTE: MoveIdentifier
SUDOWOODO: PokemonSpecies
SUICUNE: PokemonSpecies
SUNFLORA: PokemonSpecies
SUNKERN: PokemonSpecies
SUNNY_DAY: MoveIdentifier
SUPERSONIC: MoveIdentifier
SUPER_FANG: MoveIdentifier
SUPER_POTION: ItemIdentifier
SURF: MoveIdentifier
SWAGGER: MoveIdentifier
SWEET_KISS: MoveIdentifier
SWEET_SCENT: MoveIdentifier
SWIFT: MoveIdentifier
SWINUB: PokemonSpecies
SWORDS_DANCE: MoveIdentifier
SYNTHESIS: MoveIdentifier
TACKLE: MoveIdentifier
TAIL_WHIP: MoveIdentifier
TAKE_DOWN: MoveIdentifier
TANGELA: PokemonSpecies
TAUROS: PokemonSpecies
TEDDIURSA: PokemonSpecies
TELEPORT: MoveIdentifier
TENTACOOL: PokemonSpecies
TENTACRUEL: PokemonSpecies
THIEF: MoveIdentifier
THRASH: MoveIdentifier
THUNDER: MoveIdentifier
THUNDERBOLT: MoveIdentifier
THUNDERPUNCH: MoveIdentifier
THUNDERSHOCK: MoveIdentifier
THUNDER_WAVE: MoveIdentifier
TOGEPI: PokemonSpecies
TOGETIC: PokemonSpecies
TOTODILE: PokemonSpecies
TOXIC: MoveIdentifier
TRANSFORM: MoveIdentifier
TRIPLE_KICK: MoveIdentifier
TRI_ATTACK: MoveIdentifier
TWINEEDLE: MoveIdentifier
TWISTER: MoveIdentifier
TYPHLOSION: PokemonSpecies
TYRANITAR: PokemonSpecies
TYROGUE: PokemonSpecies
UMBREON: PokemonSpecies
UNKNOWN_ITEM: ItemIdentifier
UNKNOWN_MOVE: MoveIdentifier
UNOWN: PokemonSpecies
URSARING: PokemonSpecies
VAPOREON: PokemonSpecies
VENOMOTH: PokemonSpecies
VENONAT: PokemonSpecies
VENUSAUR: PokemonSpecies
VICEGRIP: MoveIdentifier
VICTREEBEL: PokemonSpecies
VILEPLUME: PokemonSpecies
VINE_WHIP: MoveIdentifier
VITAL_THROW: MoveIdentifier
VOLTORB: PokemonSpecies
VULPIX: PokemonSpecies
WARTORTLE: PokemonSpecies
WATERFALL: MoveIdentifier
WATER_GUN: MoveIdentifier
WEEDLE: PokemonSpecies
WEEPINBELL: PokemonSpecies
WEEZING: PokemonSpecies
WHIRLPOOL: MoveIdentifier
WHIRLWIND: MoveIdentifier
WIGGLYTUFF: PokemonSpecies
WING_ATTACK: MoveIdentifier
WITHDRAW: MoveIdentifier
WOBBUFFET: PokemonSpecies
WOOPER: PokemonSpecies
WRAP: MoveIdentifier
XATU: PokemonSpecies
X_ACCURACY: ItemIdentifier
X_ATTACK: ItemIdentifier
X_DEFEND: ItemIdentifier
X_SPECIAL: ItemIdentifier
X_SPEED: ItemIdentifier
YANMA: PokemonSpecies
ZAPDOS: PokemonSpecies
ZAP_CANNON: MoveIdentifier
ZUBAT: PokemonSpecies

class MoveIdentifier(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = []

class PokemonSpecies(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = []

class ItemIdentifier(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = []
